#!/usr/bin/env bash

# Check for root (in case script isn't run from setup.sh)
if [[ $EUID != 0 ]]
then
    echo "Please run as root"
else
    # Scan for users with EUID of 0 (root users)
    # Should only return one line
    echo "Users in root group:"
    awk -F: '($3 == "0")' /etc/passwd
    
    # Ask to remove all non root users from root group
    confirm.sh "Remove all non root users from root group"
    
    # Remove all non root users from root group
    if [[ $? = 1 ]]
    then
        # Gotta fill in this bit
        echo
    fi
fi