#!/usr/bin/env bash

if [[ $EUID != 0 ]]
then
    echo "Please run as root"
else
    echo "Password fields:"
    awk '-F\t' '($1 == "password") {print}' /etc/pam.d/common-password
    
    echo
    
    ./confirm.sh "Set password minlen"
    
    if [[ $? = 1 ]]
    then
        min_set=$(awk '-F\t' '$3 ~ /minlen/{print}' /etc/pam.d/common-password)
        if [[ !$min_set ]]
        then
            # Somewhat of a sketchy test, somebody gotta tell me what'll work here if this doesn't
            line=$(awk '-F\t' '$2 ~ /\[/{print NR}' /etc/pam.d/common-password)
            # Append a minlen to end of this line
            sed -i "${line}s/$/ minlen=8/" /etc/pam.d/common-password
        fi
    fi
    
    ./confirm.sh "Enforce password complexity"
    if [[ $? = 1 ]]
    then
        echo "Enforce password complexity"
    fi
fi