#!/usr/bin/env bash

if [[ $EUID != 0 ]]
then
    echo "Please run as root"
else
    echo "Password fields:"
    awk '-F\t' '($1 == "password") {print}' test_common-password
    
    echo
    
    ./confirm.sh "Set password minlen"
    
    if [[ $? = 1 ]]
    then
        min_set=$(awk '-F\t' '$3 ~ /minlen/{print}' test_common-password)
        if [[ !$min_set ]]
        then
            # Somewhat of a sketchy test, somebody gotta tell me what'll work here if this doesn't
            line=$(awk '-F\t' '$2 ~ /\[/{print NR}' test_common-password)
            # Append a minlen to end of this line
            sed -i "${line}s/$/ minlen=8/" test_common-password
        fi
    fi
    
    ./confirm.sh "Enforce password complexity"
    echo $?
fi