#!/usr/bin/env bash

if [[ $EUID != 0 ]]
then
    echo "Please run as root"
else
    echo
    apt-get update
    echo
    apt-get upgrade
    echo
    
    ./confirm.sh "Set up auto-update"
    
    if [[ $? = 1 ]]
    then
        apt-get install unattended-upgrades
        nano /etc/apt/apt.conf.d/50unattended-upgrades
    fi
fi